### ISSUE TITLE
Feature request: write_cog to explicitly define no_data_values and dtypes

### ISSUE THREAD

**Issue by BexDunn** [opendatacube/datacube-core#1004]
### Expected behaviour
`write_cog(ds, "output_file.tif",  dtype='float32', nodata=nan)`

### Actual behaviour
`write_cog(ds, "output_file.tif")`
Super lovely, but a lot of our products have problems as the nodata output defaults to zero. Eg. with NDVI, 0 means water not nodata. Explicitly stating the nodata default in the doco would help; additionally making it obvious that you can set the dtype would help. I know that rasterio arguments can be passed, but it took me about a month of using the function until I had the brains to look for this in the rasterio.open doco.....

Happy to help with this one.

**Comment by Kirill888** [comment]
Type conversion is out of scope for this function, so do `ds.astype('float32')` on input instead.

`nodata=` argument is already accepted, also it is being read from attributes dictionary, but supplied argument takes precedence over `ds.nodata`. Although it is apparently missing from documentation.

For floating point images that contain `NaN`s there is no need to define `nodata` attribute at all, but you have to ensure that `ds.attrs["nodata"]` doesn't exist also, otherwise that value will be added to output file as `nodata` value.
