### ISSUE TITLE
Datacube config file to use by default?

### ISSUE THREAD

**Issue by andrewdhicks** [opendatacube/datacube-core#103]
In the hack days, we got some feedback that the expected order of config file locations we search was unexpected.

A user was running `module load agdc-py2-dev`, which was setting the environment variable, but the config file being used was the home directory from a previous private install, pointing to a different database.

The current order is:
- datacube.conf (in the current working directory)
- ~/.datacube.conf (user's home directory)
- DATACUBE_CONFIG_PATH (environment variable)
- /etc/datacube.conf

(The default behavior is to reverse search this list, overriding parameters)

What is the expected behavior?
Should the module be doing something different?
How will any changes affect proposed support for multiple databases?

**Comment by v0lat1le** [comment]
The overriding behaviour is trouble. It can lead to mutant configurations like DB IP from one config and port from another. Easy to stuff up, hard to debug and adds no value, imho

**Comment by v0lat1le** [comment]
Config from current working directory seems dangerous. Different behaviour depending on where you run things doesn't sit well with me.

**Comment by Spaxe** [comment]
If I could put in my view, this is the order I propose:
- `datacube.api.API(<config dict>)` 
- `datacube.api.API(<config filepath>)`
- `datacube.api.API()` would default to looking at default config files:
  - `~/.datacube.conf` (user's home directory) 
  - `/etc/datacube.conf`

(If you're loading config elsewhere, feel free to replace the entry point above.)

Environment variables are hard to debug and audit. I vote to remove that option.

Reading config files from the working directory can cause import issues as @v0lat1le pointed out. I vote to remove that option as well.

Having a default config file path is good for deployment reasons, but that means you can't have two deployments in the same machine. This might not be an issue for the most part, but to the programmer the config is opaque by design.

Certainly, I'm against partially updating config dicts from two sources.
