### ISSUE TITLE
Don't use rasterio.path

### ISSUE THREAD

**Issue by sgillies** [opendatacube/datacube-core#1246]
@Kirill888 exposing rasterio.path and its members in Rasterio's public API was a mistake (https://github.com/rasterio/rasterio/issues/2365). Can you change https://github.com/opendatacube/datacube-core/blob/95e72fdbff2707aa6f7abc837d9eab52c50258e1/datacube/storage/_rio.py#L16 to not use it and to just call rasterio.open() instead?

I would love to rename rasterio.path to rasterio._path. At the very least we will warning about this in 1.3.0.

**Comment by Kirill888** [comment]
Thanks for the heads up @sgillies. At the time this was introduced, it was really just a work-around for some performance issues caused by `AWSSession` construction bugs that were long time since been fixed, I believe it was attempting to get credentials when no credentials settings were set or something like that.

@SpacemanPaul this look like it's a trivial fix: replace `DatasetReader(...)` with `rasterio.open(...)` and pass through uri as a string. So would be nice for it to be included in the next release.
