### ISSUE TITLE
Automatic creation of database users causing problems

### ISSUE THREAD

**Issue by andrewdhicks** [opendatacube/datacube-core#132]
When the agdc module is loaded, it triggers an attempt of creation of a user in the datacube database described in the module's config.  If the user did not already exist, the user is created and a password is stored.
When accessing the system from another platform with a different home directory (eg VDI and raijin do not share home folders), the password is not accessible, and a new db user account cannot be generated as the user already exists.
For read-only access to public data, the user could be configured to use no password.

**Comment by jeremyh** [comment]
The 'no password' would probably need to be implemented as a default password. I'm also hesitant about it because it will give us a more difficult migration when we do start caring about a users' identity (adding required authentication later and possibly breaking things).

Would this be an ok alternative?
- Document for users the need to copy their existing pgpass onto new machines. This isn't too different to the previous need to copy the `cube_user` information to each of their home directories.
- Improve the error message: for example, it could tell users that they already have an account, and to copy the existing `~/.pgpass`.

**Comment by mpaget** [comment]
I agree on both points. I don't believe its in its scope to build custom code to suit the "quirks" of one environment. Rather, code should be built to do "the right thing" with flexibility to allow it to be applied to different environments. A practical error message is always handy :), and in this case I think strikes the right balance for the environment in question.

**Comment by v0lat1le** [comment]
Part of the problem is that we silently generate the password for new users and put it into .pgpass.
I'll make the module log that a password has been created and added to .pgpass to raise the awareness of the process.

**Comment by jeremyh** [comment]
@mpaget: Yeah, we're specifically keeping anything too NCI-specific out of the core framework. This user-creation code is in the NCI modules, not in our Python (core) codebase. The Python codebase is agnostic to choice of Postgres authentication.
