### ISSUE TITLE
Compatibility issue - python version and  aiohttp

### ISSUE THREAD

**Issue by GeoFelpave** [opendatacube/datacube-core#1511]
### Expected behaviour

When adding odc-apps-dc-tools-0.2.14 there is an issue with aiohttp if the version of python is greater than 3.10. The main reason for this is that aiohttp for python >3.10 is currently in beta as per info here: https://github.com/aio-libs/aiohttp/issues/7675 which means that odc-apps-dc-tools-0.2.14 does not install as expected

### Actual behaviour

note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
Failed to build aiohttp
ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects

### Steps to reproduce the behaviour

mamba env create -f conda-environment.yml
pip install odc-apps-dc-tools

### Environment information

As per the .yml file here: https://github.com/opendatacube/datacube-core/blob/develop/conda-environment.yml

### Propose solution
As per the conda-environment.yml the python version is defined by python >=3.9, I would like to suggest this is change to python=3.9 or python=3.10 until aiohttp fully supports the latest python versions

**Comment by SpacemanPaul** [comment]
I'd be more inclined to fix it in odc-tools than in core, as core doesn't use aiohttp directly.

**Comment by emmaai** [comment]
Could you move the issue to https://github.com/opendatacube/odc-tools? as
- `aio-http` is not the dependency of `datacube`, not all users will require `odc-tools`
-  the python version pin can be implemented in `odc-tools`

**Comment by Kirill888** [comment]
@SpacemanPaul I think it's way more common to define python dependency as an `=` rather than `>=`, eventually newer version of python will come out and it will break again. I say put `python=3.10` in there.

**Comment by Kirill888** [comment]
I see this file as a "suggested starting point" for an environment with datacube installed, and such should probably reference "currently most stable python version", rather than a lower bound of supported python language.

**Comment by omad** [comment]
Oh, this is a can of worms!

I think this conda environment was defined before `datacube` was available in [conda-forge](https://conda-forge.org/). My usual workflow now is to run something like:

    mamba create -n newenvironment python=3.11 datacube
    mamba activate newenvironment

However, this doesn't get all the way to using odc-tools. Because, it's dangerous any time you install (binary) packages from Conda and PyPI in the same environment. Sometimes it works, sometimes it doesn't, sometimes it crashes or corrupts your data.

And when I run `pip install odc-apps-dc-tools`, it grabs a few binary wheels like scipy, and it could potentially also grab a version of aioboto3 which is incompatible with boto3.

`odc-apps-dc-tools` is available from conda-forge. However, I'm not sure it's been kept up to date, I suspect not. But it is possible to run:

    mamba create -n newenv python=3.11 odc-apps-dc-tools 
    mamba activate newenv
    pip install --upgrade odc-apps-dc-tools

And you'll get a working environment, with python 3.11, and datacube and odc tools.

**Comment by GeoFelpave** [comment]
As per @emmaai comment. I have moved this issue to odc-tools. I am incline to think that the diferents responses here showed how to deal with the issue, and made clear that this issue highlighted is not part of the datacube core deployment
