### ISSUE TITLE
Question -- combining multiple products & sensors

### ISSUE THREAD

**Issue by ceholden** [opendatacube/datacube-core#156]
Hello!

I want to congratulate and thank you all for the work toward version 2 of this project. I'm very excited to use this software. It looks like it will be very helpful in wrangling our data for existing work and will also help enable some new research (multi-sensor integration, leveraging Landsat path/row overlaps, and near real time applications). I've gotten myself setup, have indexed and ingested some data from Landsat 7 and 8, and have walked through the notebook examples for the `datacube.API` and `datacube.api.GridWorkflow` methods of accessing the data.

If you don't mind, I'm hoping you can clarify a use case that I have for the AGDC:

I indexed the Landsat data using the configuration samples inside of `docs/config_samples` for the dataset types (`ls5_scene.yaml`, `ls7_scene.yaml`, etc.) and the ingester (`ls5_ledaps_albers.yaml`, `ls7_ledaps_albers.yaml`, etc.). My understanding is that this organization means that data from these Landsat sensors are now indexed as separate "products" (as in `dc.load`'s `product` argument), but I really just want to retrieve some subset of measurements (the ones common to all Landsat sensors) for some bounding box across all sensors spanning the entire history of the Landsat archive. 

Some of the example notebooks (which I might be misunderstanding or might be out of date) suggest this sort of thing is possible. For example,
- the [WOFS notebook](https://github.com/data-cube/agdc-v2/blob/develop/examples/notebooks/wofs_sample.ipynb) shows a query for one product (`ls5_nbar_albers`) across multiple sensor platforms (`platform=['LANDSAT_5', 'LANDSAT_7', 'LANDSAT_8']`)
- the [older "Catapult Project" notebook](https://github.com/data-cube/agdc-v2/blob/2f65c2cdfb8553015e298983b603b1adde686cb6/contrib/notebooks/Catapult%20Project%20-%20Navigating%20AGDC%20v2.ipynb) shows a query for one product, `gamma0`, across multiple platforms (`['ALOS_2', 'SENTINEL_1A']`)

The WOFS example query, however, only shows data retrieved from Landsat 5, and this is the experience I've had as well. Do you have any guidance for performing such a query, which ideally would return a single `xr.Dataset`, perhaps with the platform name given as a coordinate along the `time` dimension? I'm describing my ideal use case, but is there an easy way to achieve something similar that I'm missing?

I'm currently doing the following to merge the datasets:

``` python
products = ['ls7_ledaps_albers', 'ls8_ledaps_albers']

# Find measurements common to all products
measurements = dc.list_measurements().reset_index()
measurements.index = measurements['product']
data_vars = set(measurements.loc[products[0], 'measurement'])
for prod in products[1:]:
    data_vars.intersection_update(measurements.loc[prod, 'measurement'])

# Read each product individually
datasets = []
for prod in products:
    ds = dc.load(product=prod,
                 product_type='LEDAPS',
                 platform=['LANDSAT_5', 'LANDSAT_7', 'LANDSAT_8'],
                 measurements=data_vars,
                 x=(-72, -71.90), y=(41., 41.10))
    ds['platform'] = ('time', np.repeat(prod, ds.time.size))
    datasets.append(ds)

# Concat along time
combined = xr.concat(datasets, dim='time')
```

spits out

``` python
> combined
combined
<xarray.Dataset>
Dimensions:       (time: 61, x: 364, y: 432)
Coordinates:
  * y             (y) float64 2.263e+06 2.263e+06 2.263e+06 2.263e+06 ...
  * x             (x) float64 1.979e+06 1.979e+06 1.979e+06 1.979e+06 ...
  * time          (time) datetime64[ns] 2013-10-01T15:22:55 ...
Data variables:
    red           (time, y, x) int16 20 -2 20 64 43 43 20 64 -9999 -2 87 20 ...
    swir1         (time, y, x) int16 8 8 8 -20 -20 8 8 8 -9999 8 8 8 -9999 ...
    swir2         (time, y, x) int16 50 50 -10 -10 19 80 19 -10 -9999 19 19 ...
    nir           (time, y, x) int16 -10 -42 23 23 -10 -42 -10 -10 -9999 23 ...
    cf_mask_conf  (time, y, x) int16 1 1 1 1 1 1 1 1 255 1 1 1 255 255 1 255 ...
    green         (time, y, x) int16 187 160 134 187 134 187 134 187 -9999 ...
    blue          (time, y, x) int16 235 186 186 211 186 235 211 161 -9999 ...
    platform      (time) <U17 'ls7_ledaps_albers' 'ls8_ledaps_albers' ...
    cf_mask       (time, y, x) int16 1 1 1 1 1 1 1 1 255 1 1 1 255 255 1 255 ...
Attributes:
    crs: EPSG:5070
```

Is there a better way of retrieving multiple products with a single API call that I'm missing, or is this sort of thing up to the end user? I guess the other alternative is to configure the dataset configuration files to create a unified "Landsat ESPA Data" product of sorts, but this would probably eliminate all the lovely sensor specific metadata that can be stored when setup as separate products.

Meta question -- is there a better place to ask these questions? Gitter? Slack? Mail list?

Thanks
Chris

**Comment by v0lat1le** [comment]
Hi Chris.

What you're doing is the only way to do it right now. We are trying to get something like that in the API, but there are many edge cases and the API gets unwieldy really fast...

You don't need to specify `product_type` and `platform` in this case, since `product` already carries that information. We'll update those notebooks so they are not so confusing.

You might also want to use `group_by='solar_day'` parameter to mosaic consecutive scenes and eliminate duplicate data on overlaps.

We'll send you an invite to our slack channel.

**Comment by llymburn** [comment]
Hi Chris,

It would be worth having a look at the https://github.com/llymburn/JupyterNotebooks/blob/master/Datacube_Hov_vis_v3.ipynb

This notebook shows how to grab surface reflectance from 3 sensors, then concatenate and sort by time to generate multi-sensor time series (complete with the opportunity to apply sensor specific adjustment prior to concatenation).  It’s also got the PQ fuse syntax you’ll need to mask out PQ in the N/S overlaps (a more enduring bug fix is on it’s way for this one, but it’s worth using this for now).

Picking up on an earlier email thread, it looks like you were able to demo CCDC and TS tools to Brian based off this AGDCv2 API.  If there’s a Jupyter notebook that you could share that shows either of these capabilities (or a script that will allow us to do similar things using QGIS) that you would be amenable to sharing, that would be a great contribution to the overall data cube development activity.

Kind regards,

Leo Lymburner PhD
Data Cube Product Development Team Lead  |  National Earth and Marine Observation Group
Environmental Geoscience Division  |  GEOSCIENCE AUSTRALIA

---

Phone:  +61 2 6249 9587    Fax:  +61 2 6249 9999
Email:  Leo.Lymburner@ga.gov.aumailto:Leo.Lymburner@ga.gov.au    Web:  www.ga.gov.auhttp://www.ga.gov.au/
Cnr Jerrabomberra Avenue and Hindmarsh Drive Symonston ACT
GPO Box 378 Canberra ACT 2601 Australia
Applying geoscience to Australia’s most important challenges

**Comment by llymburn** [comment]
Hi Leo & Gregory!

Thanks to you and the extended AGDC team for the outpouring of replies to
my query. I received the Slack invite and look forward to asking stupid
questions and chatting with you all.

From looking over your notebook, it seems like I'm on the right track with
combining multiple sensors. I've only toyed with the pixel quality masking
in reproducing one of the example notebooks in the AGDC repo, so your
notebook will be very useful as an extension from that example. Also,
thanks for the reminder about the "group_by" -- don't want any pesky N/S
overlap!

Back in early June (?), I hacked together a "time series driver", a Python
class that conforms to an expected API within TSTools and handles the
reading of a dataset format (e.g., the 100s of "stacked" images sorted into
directories we use at BU), that enumerated the various NetCDF files
covering a Datacube tile so that one could visualize all optical spectral
bands (blue, green, red, nir, swir1, and swir2) as a 3-band RGB
multispectral image and also plot the observations from a "pixel drill" by
clicking around in the image.

At the time, none of this was accomplished using the AGDC API -- I simply
opened and read from the metadata rich NetCDF files produced from an
ingest. The first bit of tech -- visualizing multiple measurements as RGB
images for individual acquisition dates -- was accomplished by producing
GDAL-compatible VRTs that played nicely with QGIS. The second feature --
the "pixel drill" -- was done using xarray and dask, but not with the AGDC
API. With your answers today to my Github ticket, I'm basically done with
the research to accomplish these two goals using the AGDC API. I still
haven't figured out a way around using VRTs of the underlying NetCDF files
for the multi-band representations (because AFAIK QGIS isn't great with "in
memory" rasters), but using the API allows me to more easily locate these
NetCDF files and makes the "pixel drill" functionality very easy.

I'm quite tardy in getting to this point (sorry, Brian!), but all of this
work is going up on Github and I'd be more than happy to share whatever I
come up with, either as part of TSTools or separately.

As far as CCDC goes, TSTools is really only useful in visualizing
pre-calculated results or experimenting with model parameters to produce
results on a pixel-by-pixel basis. In practice it takes something like 300
CPUs most of a day to run a single Landsat path/row time series stack.
There are currently three implementations of CCDC floating around -- Zhe's
latest development in MATLAB, the "C-CCDC" port of Zhe's MATLAB code into C
by the USGS LCMAP team (available on Github) which will eventually become
stable and usable, and my Python "CCDCesque" port which approximately
targets the version of CCDC used in Zhe's 2014 paper with some alterations
and optional enhancements.

Once the C-CCDC code becomes stable, I will wrap it using Python and
incorporate it YATSM (Yet Another Time Series Model), a Python codebase we
use for running our latest development work, including work using the
"CCDCesque" port. I'm currently in the process of revamping YATSM to
utilize some of the latest and greatest tech from Continuum Analytics,
PyData, etc, including libraries that AGDC is using (xarray, dask,
distributed). Once this is accomplished, I aim to use the AGDC API as a
"backend" to read in time series information in place of reading our
"stacked datasets" with GDAL/rasterio. Basically, I could only provide an
example of running my "CCDCesque" port for a single pixel retrieved from
AGDC right now if it would be helpful, but in the future I hope to use AGDC
as the backbone of all our processing. I'm not quite sure where the AGDC
execution or analytics engine is going, but running complicated pixel-based
time series analysis at scale will likely require "dask.delayed", much in
the same way that they're parallelizing scikit-learn estimators with this
tech.

IIRC next Landsat Science Team is in Boston! Hope to see you there!

Chris

**Comment by ceholden** [comment]
Thanks everyone -- I think I have it all sorted. Answer is that users should `xr.concat` each product's retrievals in the short run, but there might be some assistance via the API in the future. For now, Leo's notebook is very instructive:

https://github.com/llymburn/JupyterNotebooks/blob/aa8e0592fc4f1dfeae59ad1925df06cb3f1b4bbf/Datacube_Hov_vis_v3.ipynb
