### ISSUE TITLE
Error Writing to netcdf 

### ISSUE THREAD

**Issue by conicRelief** [opendatacube/datacube-core#161]
I've run into an error:  

ValueError: Failed hard to prevent overwriting key 'units'
  
I'm not sure what this is or why I'm running into it.   
The process for reproducing this:  
  
- Perform `dc.load( ...params...)`
- run `.to_netcdf(path = 'test.cd')`

**Comment by v0lat1le** [comment]
In this particular case it's the `units` attribute on the `time` coordinate that trips up xarray.

Generally `to_netcdf` wouldn't work with Datacube xarrays since we put other metadata (like `crs`) in that xarray wouldn't know how to deal wtih.

You could try using `datacube.storage.storage.write_dataset_to_netcdf`
