### ISSUE TITLE
Specify Resampling Algorithm when Ingesting

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-core#18]
The resampling method for ingester should support the following:
- near: nearest neighbour resampling (default, fastest algorithm, worst interpolation quality).
- bilinear: bilinear resampling.
- cubic: cubic resampling.
- cubicspline: cubic spline resampling.

At the moment there is a space for **interpolation** in the `storage_config.yaml` file used to specify the output of an ingestion process. It's currently being ignored by the ingester.

This will be replaced with an option to specify a **resampling** algorithm, as implemented by gdal. The allowed options are based on http://www.gdal.org/gdalwarper_8h.html#a4775b029869df1f9270ad554c0633843.

**Comment by omad** [comment]
@simonaoliver , can you please look at the list from GDAL and determine which resampling algorithms we need to support. In an effort to have more verifiable tasks to complete.

**Comment by woodcockr** [comment]
Would be worth taking a look at pyresample as well  https://pyresample.readthedocs.org/en/latest/

**Comment by sixy6e** [comment]
As a minimum, I'd say:
    Nearest Neighbour
    Bilinear
    Cubic
    Cubic Spline

Nearset is the main one currently in use for ingestion, purely because of the categorical nature of PQ.

rasterio has a method to tap into the GDAL library and perform on a NumPy array.  We tapped into it for NBAR processing, https://github.com/GeoscienceAustralia/ga-neo-landsat-processor/blob/develop/gaip/data.py#L391

pyresample looks good, but transpositions will need to occur for 3D data.  It does allow blocking in order to reduce memory footprint, but I'm not sure if one still needs the original image in memory in order to process the result,, which would not be ideal.
