### ISSUE TITLE
Ability to identify and track versions of a single dataset

### ISSUE THREAD

**Issue by GypsyBojangles** [opendatacube/datacube-core#193]
This has always been planned, and we've discussed it, but haven't prioritized it enough to implement.
If a dataset is reprocessed (for example, after updated ancillary arrives), it should "replace" the old one. The old dataset will still remain in the index for provenance, but not be returned in queries. Currently this will result in a duplicate dataset unless you manually archive the replaced dataset.

**Comment by Kirill888** [comment]
@GypsyBojangles I guess by "replace" you mean "index new version and also archive old version in one step". Since there is no way to "actually replace" dataset, since uuid of a new dataset ought to be different from the old one.

What is needed then is a way to track previous versions of the dataset. If, say, we had a field `replaces = uuid-of-previous-dataset` then we could do extra steps during indexing:

1. Archive (if not already) dataset with `uuid-of-previous-dataset`, possibly after doing some sanity checks like: roughly same space and time is covered by the two datasets.
2. Record "previous version relation", similarly to the way we currently do "lineage".

Addressing this however requires actually defining metadata spec and db schema migration strategy, as this will require another table to record previous version "linked list".

**Comment by GypsyBojangles** [comment]
@kirill888 this is a very old issue, it either preceeded me and i copied it over from Jira or it was raised in my first month on the project. Re-reading this I feel like between dataset archive and our sync tool it’s easy enough to work around this in practice. Up to you and @omad if you want to keep this issue.

**Comment by Kirill888** [comment]
@GypsyBojangles, @omad archive and sync deal with consistency of the current state of the database, they do nothing to track versions of dataset, not sure if tracking dataset versions was part of the motivation for this issue when created and whether this is still of interest today.

If we had standardised region identifiers as proposed in #536 the job of checking for accidental duplicates would be much easier, it would also allow safer dataset management as it would make options like: "automatically find and archive previous version of this dataset"  more feasible without forcing it on user/external tool.

There is a common theme with all of these "proposals": none of them can proceed because there is no place to store extra data. We have this "metadata" indirection layer and everything must go through that to be searchable, but that layer is supposedly custom per product (in practice everyone uses `EO`) and we lack any structure that is product independent, even `id`, which is a compulsory field and must contain UUID was previously "indirected" by the metadata layer making it impossible to make any claims about dataset document until it is "matched to a product in a database".

**Comment by alexgleith** [comment]
If this has yet to be implemented, then I feel like there's no clear use-case and we should probably close the issue.

**Comment by Kirill888** [comment]
lets close it, we might add "dataset version tracking" to ODC 2.0 proposal if there is interest.
