### ISSUE TITLE
Rename make_dataset extent argument

### ISSUE THREAD

**Issue by GypsyBojangles** [opendatacube/datacube-core#196]
We should try to select names that are consistent within the codebase. This would improve maintainability for future developers.
For example, the `extent` argument of `datacube.model.utils.make_dataset` and the `extent` property of a `datacube.model.Dataset` object refer to different concepts. One intends the maximal rectangular extent of the array (aka. _bounds_), and the other intends the extent of a tighter envelope which excludes parts of the array that only contain nodata values (aka. _valid_data_).
Similarly, e.g. `xarray.Dataset` versus `postgres agdc.dataset table versus datacube.model.Dataset`..

**Comment by Kirill888** [comment]
@GypsyBojangles 

I think the issue is that `make_dataset` takes either/or/both "bounding box" (`extent`) as well as "valid region" (`valid_region`). The whole thing is completely broken see #537. And really requires a proper fix to handling of geospatial data within datacube: 

https://github.com/orgs/opendatacube/teams/developers/discussions/5
