### ISSUE TITLE
Different behaviour according to dependency version (which depend on conda channels)

### ISSUE THREAD

**Issue by rtaib** [opendatacube/datacube-core#208]
Pulling dependencies from the default conda repo doesn't work, in particular the following test fails:
```bash
AttributeError: 'NoneType' object has no attribute 'Segmentize'` in `datacube/utils/geometry.py:448`
```
which is in:
```python
	clone = _chop_along_antimeridian(clone, transform, rtransform)
```
with the `_chop_along_antimeridian` call itself segmentizing, transforming and intersecting on simple hand-made polygon geometry. With default conda channel modules (incl. gdal 2.1.0 as of today) `clone` gets set to `None`, while with the conda-forge channel (incl. gdal 2.1.3 as of today), it gets set to a proper geometry and the test passes. I didn't look in details, but if the difference is due to a non-deterministic geometric operation according to dependecy version, then that's alarming. I hope it's something else, but even so, you don't want behaviour to change so much between dependencies' versions, so it may be worth looking into it at some point.

To reproduce:
- Install an environment using the [travis dependencies](https://github.com/opendatacube/datacube-core/blob/develop/.travis/environment_py35.yaml) but WITHOUT prepending the conda-forge channel beforehand.
- Run the full integration tests `./check-code.sh integration_tests`, or simply `pytest tests/test_geometry.py`.

**Comment by v0lat1le** [comment]
`defaults` channel is missing some of the required packages and some of the critical packages are out of date, that's why the documentation suggests using `conda-forge`.

It is likely that datacube will always require the latest versions of some packages (e.g. gdal, rasterio) because their bounaries are pushed by the new datacube features and bugs in them are discovered and fixed.

Is there any reason you can't use `conda-forge` channel?
