### ISSUE TITLE
Print an error msg "NameError: name 'gdalversion' is not defined" when I run setup.py install on my windows

### ISSUE THREAD

**Issue by asqhaqs** [opendatacube/datacube-core#221]
File "C:\Users\01\AppData\Local\Programs\Python\Python35\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Users\01\AppData\Local\Programs\Python\Python35\lib\site-packages\setuptools\sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "C:\Users\01\AppData\Local\Programs\Python\Python35\lib\site-packages\setuptools\sandbox.py", line 285, in run
    return func()
  File "C:\Users\01\AppData\Local\Programs\Python\Python35\lib\site-packages\setuptools\sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "C:\Users\01\AppData\Local\Programs\Python\Python35\lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "C:\Users\01\AppData\Local\Temp\easy_install-ry9c1r3q\rasterio-1.0a8\setup.py", line 134, in <module>
NameError: name 'gdalversion' is not defined

**Comment by jeremyh** [comment]
Hey 2015E8007061068, thanks for the report.

It looks like this is coming from rasterio, one of our dependencies — a minor bug [in their setup.py](https://github.com/mapbox/rasterio/blob/994def271a14126e690a080ead816626a70fdeb0/setup.py#L134), when displaying the following error message:

    A GDAL API version must be specified. Provide a path 
    to gdal-config using a GDAL_CONFIG environment variable 
    or use a GDAL_VERSION environment variable.

To get around it, you likely need to install gdal or point one of those environment variables to an existing install. Otherwise, [we recommend conda ](https://datacube-core.readthedocs.io/en/latest/ops/conda.html) as a much easier install method than straight pip (which bundles libraries like gdal).

**Comment by jeremyh** [comment]
Fix in mapbox/rasterio#1013

**Comment by jeremyh** [comment]
Prroposed error message fix in mapbox/rasterio#1013

**Comment by DrewDevereux** [comment]
The cause of the error is that rasterio setup.py needs to know what gdal version is installed. It tries to get that information from the gdal-config executable, but gdal-config is a *nix thing and does not exist on Windows installs of gdal. The rasterio build instructions say that if you're building on Windows then you have to specify the gdal version in an extra parameter to setup.py. As such, this is not a rasterio bug. The problem is that _our_ setup.py is not providing that extra parameter, so _our_ setup.py will never be able to build rasterio on Windows.

The workaround is of course to preinstall gdal and rasterio. If using conda, then the guidance given to 
`conda config --add channels conda-forge`
is particularly important, because if overlooked then conda will only find and install gdal 1.8. Since our setup.py requires "gdal>=1.9", it will reject the installed version, try to build it itself, and hit the aforementioned issue again.

**Comment by jeremyh** [comment]
Hi Drew,

You’re right that rasterio didn’t cause the problem — the rasterio bug I referenced is that it’s throwing an exception rather than printing a helpful error message (as its code is written to do). That error message points out that you can set the GDAL_VERSION environment variable to specify the version.

Whether we want to accept and pass along the “--gdalversion” flag too, as you suggest, I don’t know. I couldn’t see other projects in a brief search that handle this case, but it might be more friendly.
