### ISSUE TITLE
Sample application demonstrating Analytical Engine

### ISSUE THREAD

**Issue by v0lat1le** [opendatacube/datacube-core#23]
Implement an application (or applications) demonstrating Analytical Engine (#22)

Something involving simple band maths and/or statistics over time

**Comment by woodcockr** [comment]
#15 has a dask implementation which seems redundant now the intent is to join this to the analytical engine. Should #15 demonstrated functionality be incorporated here and deprecated?

**Comment by v0lat1le** [comment]
@woodcockr I guess once analytical engine is integrated. For now we still need something that lets us design the low level API's

**Comment by woodcockr** [comment]
Sounds like all the more reason to work with the Analytics Engine to design the low level APIs, otherwise how do you know what is needed?

**Comment by sixy6e** [comment]
From the analytics engine document that was circulated, it appears that it is working on in-memory objects/arrays.  Is that still not the case?

**Comment by woodcockr** [comment]
If you are referring to the EDA on a single Node AGDCIP then you are reading only 1 of 3 AGDCIP, the first of which is for single compute node support. The others were flagged as coming and will complete the suite of requirements as listed in v2 - which means out of core memory support and parallel and distributed processing. The first one was multi-core support on single node (and yes it can do out of core memory).
Underneath xray+dask are used to provide this: see https://www.continuum.io/content/xray-dask-out-core-labeled-arrays-python for a quick overview of capabilities.

Note that since xray+dask are intended to work with contiguous arrays (out of core memory) the semantics don't quite match the data cube when working with more than one sensor type, spatial, temporal resolution or even differing storage units (since they can have different acquisition times in them) - same is true of numexpr, etc of course. The AGDC Analytics Expression Language provides a method for the AGDC to "intervene" in the mapping between the desired expression and its execution - which means the execution can be performed against the Data Cube semantics to split the work into lower levels of computation which boil down to array math handled by xray and dask. For a contiguous set of Storage Units this will boil down to xray+dask doing the heavy lifting. For something more interesting like a continental scale the execution engine would break it up into task scheduling working against contiguous storage units (which xray+dask handle).

Hopefully this can be extended to handle "windows" of data rather than just per pixel band math. I certainly can't see why not and the approach allows us to leverage the great work being done by a bunch of other people on xray+ dask.

That's my understanding but @peterwa knows more than I do at this point.

**Comment by sixy6e** [comment]
Cool, so we can work on the basis that the current version is expecting arrays and write it accordingly, which could just as easily be a "window" of data.

**Comment by woodcockr** [comment]
Note that "array" needs to be an xray+dask array object, or it will simply be treated like numpy and thus in memory, not lazily evaluated, etc.The key is to delaying loading and evaluation of the operators until the execution plan is worked out and preferably your out on the node with local scratch space to hold on the temporaries. -> and at this point you need @petewa for details.

We will need to think about the different options on what to do when a Window boundary crosses a Storage Unit boundary (in any dimension) and there's no equivalent data across the boundary (e.g. different observation time, resolution, ...). Most of the time it will probably be "No data" fill, or "edge value pad" or something sane.

**Comment by sixy6e** [comment]
Now that sounds like the execution engine should wait until an I/O api is put together so it can handle non-contiguous storage and window boundary conditions, rather than assuming that each block is to be read.

One of the v1 mechanisms was to treat each storage unit independently and combine at the final stages.  That could be a 1st simple approach while the concept of a "window" as one virtual object comprising of many storage units is investigated later.

**Comment by woodcockr** [comment]
I suspect more the other way - there is an existing I/O API which the Storage access module needs to use (netcdf based, plus the dask and xray handling of out of core memory access). xray and dask already handle window boundary conditions and non-contiguous storage across multiple netcdf files. The trouble is if you load up one huge continental all of time array you will have a LOT of "No data" values or pads by default with xray. Better to handle that level of detail as part of the execution plan with Data Cube semantics.

This is why the storage access module can't be written in isolation of the execution engine as the two link quite intimately when doing out of core access, leveraging existing I/O APIs and creating parallelism. It's why v2 workshop design outcomes talks about passing around Descriptors rather than actual data and deferring access until on the computational node.

**Comment by v0lat1le** [comment]
I'm happy to work with @petewa on designing the data access api and the analytics engine. The current data access API is in this repository with tests and examples. It is designed with out-of-core processing in mind and deals in xray arrays once the data is in memory. All input into it is welcome.

**Comment by petewa** [comment]
I have originally planned to have the get_data call deeply embedded in the Execution Engine for the reasons Rob pointed out. We need to get the interface for the data access api sorted out fairly soon.

Keeping in mind, the storage units may be on S3, EBS and other storage mediums and the data access api needs to seamlessly work with different storage mediums.

We should discuss the interface between the data access api and the analytics engine.

You can sort out the design on your side of the interface with the data access api and I'll do the same on my side with the analytics and execution engine.

We need to have a chat about this, perhaps face to face with a whiteboard or over Skype?

Regarding the original issue #23, I'll do the following:
- pre-integration of analytics language
  - ndvi + median reduction examples from the gdf trial (this is on govdex but I'll put it as code examples)
  - ndvi + median reduction with analytics language test code (ndexpr) (already in code but I'll create new code examples for this)
- post-integration of analytics language
  - ndvi + median reduction for EDA

*edit: removed HPC / Multi-cloud.

**Comment by petewa** [comment]
I have uploaded sample applications for the following: 
- pre-integration of analytics language
  - ndvi + median reduction examples from the gdf trial
  - ndvi + median reduction with analytics language test code (ndexpr).

They are located:
    - https://github.com/data-cube/agdc-v2/tree/peter/ndexpr/examples/analytics_execution_engine
        - create_array.py
        - generic_ndvi.py
        - sensor_specific_ndvi.py
        - median_t.py
        - median_xy.py
        - chain_ndvi_median.py
    - https://github.com/data-cube/agdc-v2/tree/peter/ndexpr/examples/ndexpr
        - ndvi_mask.py
        - ndvi_mask_median_reduction.py

If you need more examples please let me know.

Examples of post-integration of analytics language will happen after December.
Examples of Analytics Engine & Execution engine for HPC and multi-cloud after that.

**Comment by petewa** [comment]
Here are the examples post integration of the analytics language into AE/EE.

https://github.com/data-cube/agdc-v2/tree/peter/integration/examples/analytics_execution_engine
https://github.com/data-cube/agdc-v2/tree/peter/integration/examples/ndexpr

All examples of AE/EE have been supplied.

The AE/EE is currently using the GDF and will use the new Data Access API when it's ready.

**Comment by v0lat1le** [comment]
covered by #47 #48 #49 #50
