### ISSUE TITLE
Index should not support serialization

### ISSUE THREAD

**Issue by uchchwhash** [opendatacube/datacube-core#285]
As the `_db` attribute of a `datacube.index._api.Index` object refers to a `PostgresDb` connection, it should not support serialization.

### Expected behaviour
The following code should raise a `TypeError`:

```python
import pickle
from datacube import Datacube

dc = Datacube(app='issue285')
pickle.dumps(dc.index)
```

### Actual behaviour
Trying to serialize a `PostgresDb` object only issues a warning:
`Serializing PostgresDb engine postgresql://ia1511@130.56.244.105:6432/datacube`

### Steps to reproduce the behaviour
The interaction of this issue with logging may lead to unexpected behavior. In the current `develop` branch, the above code raises an exception:
```
TypeError                                 Traceback (most recent call last)
/g/data1/u46/users/ia1511/Work/code/issue285/test-simple.py in <module>()
      3 
      4 dc = Datacube(app='issue285')
----> 5 pickle.dumps(dc.index)

TypeError: can't pickle _thread.RLock objects
```
when run in `ipython`, but not when run by the `python` interpreter.

When logging is turned on:
```python
from logging import getLogger, StreamHandler
import pickle
from datacube import Datacube

logger = getLogger(__name__)
logger.addHandler(StreamHandler())

dc = Datacube(app='issue285')
pickle.dumps(dc.index)
```
both interpreters throw the `TypeError`. Note that, in principle, the issue is not just that `RLock` objects cannot be serialized, but that currently `Index` objects can.

### Environment information

* Which ``datacube --version`` are you using?
  - stable: `Open Data Cube core, version 1.5.2`
  - develop: `Open Data Cube core, version 1.5.1+150.g71175f1.dirty`

* What datacube deployment/enviornment are you running against?
`agdc-py3-prod/1.5.2`

**Comment by jeremyh** [comment]
Thanks for the report Imam. 

I can't seem to reproduce that script you give using the `agdc-py3-prod` stable 1.5.2 module. Does it only affect develop?

My suspicion is that it's coming from pickling the `DriverManager` instance, not the `PostgresDb` instance. The latter defines ` __getstate__/__setstate__` methods for pickling, which is where we're logging the `Serializing` warning  from: but those are only serializing the string URL of the connection, not their connections/locks<sup>1</sup>.

In develop (but not stable) an instance of `DriverManager` is being stored on the `Index` instance too, under the [DatasetResource](https://github.com/opendatacube/datacube-core/blob/4dd84c6b70c26e937f988be92ec6cf4e3a665a60/datacube/index/_datasets.py#L625). It [seems to](https://github.com/opendatacube/datacube-core/blob/4dd84c6b70c26e937f988be92ec6cf4e3a665a60/datacube/drivers/manager.py#L72) contain a logger among other things, which I suspect is where that lock is coming from (especially since logging differs between environments, matching the inconsistent behaviour you're seeing).

<sup>1</sup> The PostgresDb serialization methods should be serializing the other connection arguments too, like application name; but that shouldn't affect this issue.

**Comment by uchchwhash** [comment]
Since we have identified the real issue and now there is a test in place to try to prevent that, should we probably close this? I should probably also note here that part of the issue is that `cloudpickle>=0.4.0` works just fine.

Asking @jeremyh and @Kirill888 in particular.
