### ISSUE TITLE
Pangeo and Data Cube Introductions

### ISSUE THREAD

**Issue by jhamman** [opendatacube/datacube-core#359]
Hello Data Cube Developers - 

I've recently run into the Open Data Cube project and I'm encouraged to see that it shares many of the same underpinnings as the [Pangeo Data project](https://pangeo-data.github.io/). In particular, as part of the Pangeo project, we are building out the integration of Xarray with Dask-distributed on both HPC and Cloud computing platforms.

I'm opening this issue to make the connections between the two projects and to see if there are specific areas where the two projects may leverage each others development efforts. Some topics that may be useful to discuss if/where there is interest:

- Xarray
- Dask and Dask-distributed
- Jupyter and JupyterHub
- Cloud computing and data storage/access
- Data discovery

xref: https://github.com/pangeo-data/pangeo/issues/96

**Comment by woodcockr** [comment]
Hi Jhamman

Thank you for your interest and connection. Coincidentally a colleague of mine working on ODC recently sent through information on the Pangeo Data project noting the same things you have done.

I'd certainly be interested in following up on most (all in fact) of your topics. We use xarray and have been testing Dask and Dask-distributed on and off. Jupyter and Jupyter Hub are, well they are awesome. We've been trying out some different ideas on the data storage and access with AWS S3 as well.

I'll send you an email rather than follow up in the issue area of ODC and see what we can set up to further the conversation.

Cheers

Rob
