### ISSUE TITLE
No error on dc.load if product requested doesn't exist

### ISSUE THREAD

**Issue by CEKrause** [opendatacube/datacube-core#367]
### Expected behaviour
If the requested product doesn't exist (i.e. typo, renamed etc), I would expect an error telling me the product doesn't exist.

### Actual behaviour
`dc.load()` works without error, but just returns an empty xarray.

### Steps to reproduce the behaviour
While accessing the WOFS datacube. The product was renamed to `old_wofs`. I was trying to call the product by an older name. The load "worked" but loaded nothing.

**Comment by omad** [comment]
This should have been remedied in #402.

It's slightly more complicated than expected, because the way a product is resolved in a search, can be more complicated than simply matching `product=` to the name of the product. It's possible to for example specify `platform=`, along with some other terms which restrict.

Hopefully this change makes things more usable, and doesn't create any extra confusion.
