### ISSUE TITLE
Local eager load should fail earlier when requesting "too large region"

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#383]
### Expected behaviour

When requesting to load region larger than available memory `dc.load` should fail quickly before attempting to read any data.

### Actual behaviour

`dc.load` spends considerable amount of time loading some of the data, then eventually fails due to out of memory errors. If say you requested to load bands `red,green,blue,nir`, but you only have enough memory to hold `red,green,blue`, `dc.load` will allocate and load data for the first 3 bands (one at a time), but then will fail while trying to allocate memory for the last one. It can take minutes to find out your request is too large. 

### Proposed Solution

- Allocate destination array ahead of time for all the bands of interest, and only then start loading data into pre-allocated storage. Ideally allow user to supply pre-allocated output as well.

- Provide convenience methods for estimating memory needs for a given query result

**Comment by woodcockr** [comment]
Is this approach to error handling assuming dc.load is "into memory on a single machine" or "into memory on a distributed cluster", or "into memory as needed (lazy loading) and data cube figure out how to load that up with out memory concerns"?

The Expected behaviour is certainly correct.

The convenience methods proposed solution makes sense in all three cases I just badly described.

I don't like the allocate destination array ahead of time as it seems to assume a single machine which is precisely the type of deployment dependency the ODC API should hide. Re-reading it, perhaps "Check potential allocation of destination array..." is a better phrasing. It can be a function call then - in the single machine case it could be allocated, in a distributed array scenario it could run a function call for all the nodes to see if they are able to hold their portion (either allocating or not as the case maybe), for the "data cube figure it out version" a function again would allow the ODC execution to figure out a way to do it (combo of disk and ram, dask array style).

Looks to me like an "allocation check function before load function" would give the necessary hook point for different deployment methods.

**Comment by emmaai** [comment]
Can we just write a C extension simply saying alloc() defined by the size of data? If it fails, then return an error.

**Comment by Kirill888** [comment]
@woodcockr, I meant non-lazy version, the one that actually allocates all the needed memory, eventually. That version simply can not succeed if too much is requested and so should fail sooner. Note that process can still fail with "out of memory" errors, even when main data store has been allocated successfully.

The "lazy version",  the one that uses dask is a separate issue. The whole point of that one is to pretend to have all the data loaded, but only load chunks of data as they are needed.

There is no magical "load into distributed memory" option, unless you use "dask" version that way I guess, maybe..

**Comment by woodcockr** [comment]
> There is no magical "load into distributed memory" option

Potentially is in the ODC Execution Engine and S3. datacube.load() would be against the EC2 cluster, not a single node, like dask.

I'm proposing that the datacube.load() API should support the alternate deployment modes and not assume memory allocation is against a single node. Seems simple enough to add an allocation check function so ensure we can do this consistently regardless of memory handling options.

These slight differences in design concepts are tripping us up a bit so getting in early with this one.

**Comment by petewa** [comment]
@kirill888 & @woodcockr, I agree with both of you but on different levels.

@kirill888, I believe is talking about the lower level eager dc.load() on a single instance/node. This is required no matter how you look at it. At some point in the dc.load() chain, it needs to load data into memory on a single instance, hence the utility of PR.
@woodcockr is perhaps? talking about a higher level Module/API that handles a load & compute over multiple instances. This will still need the lower level single instance dc.load() per instance. Perhaps another PR?

Knowing how many bytes of memory a dc.load would consume for a single instance would be good. The Module/API @woodcockr is talking about could use this information to determine the total usage per instance and thus, across multiple instances. The ODC Execution Engine is designed in a such a way that plays nice with this. It's good to know the overall usage, but it's more important to know whether each per instance dc.load() fits in local memory.

Back on topic:
@Kirill888, this is a great idea. This has always been at the back of my mind, but never found the time.

This shouldn't be hard to do:

The min size in bytes required would be (sources.shape) * (geobox.shape) * (sizeof(dtype)) * number_of_bands + metadata_size. More if wrapped as a python numpy array or a xarray dataset/dataarray.

Of course, this is the lower bound due to potential driver inefficiencies.

A shared memory array could be used to reduce the overhead in the creation of temporary arrays and concurrent IO.

The S3 driver does some of this, but not perfectly. It has enough indexed metadata to work out how much IO and pixels is required for a given dc.load.

An alternative way for dc.load() to operate: **Load into a shared memory array on disk**. Still, knowing how many bytes required is beneficial.

**Comment by Kirill888** [comment]
Estimating query result size in bytes of output pixels is beneficial in many use-cases:

- Work cluster sizing
- Approximating disk/network load based on average compression ratios
- Debugging and benchmarking

Back to `load_data` function that eventually gets called by `dc.load`. Confusingly `load_data` has two independent implementations under the hood (with some common code sharing):

- Actual `load_data`, goes to disk/network resource and loads requested pixels, one band at a time, one time slice at a time, also does "data deduplication step", i.e. group by solar day.
- Dask version of "load data", that doesn't load any data at all and instead constructs a dask array, which is basically a recipe for how to load data on demand as user access it.

This issue relates to the first version of `load_data`, the one that actually loads pixel before returning. At the time it is being called it knows already what shape and type the output `xarray.Dataset` will be, but rather than allocating that first and then loading data into pre-allocated storage, it interleaves data loading and memory allocation which leads to long time to failure.

I'm not interested in a solution that just adds a heuristic check on whether this particular load is likely to succeed or fail. Proper solution requires pre-allocating destination storage, however that requires significant internal code restructuring, also I suspect `skip_broken_datasets=True` might interact with that somehow.

**Comment by petewa** [comment]
"Proper solution requires pre-allocating destination storage" - I like the sound of this.

**Comment by woodcockr** [comment]
@petewa You are correct, I am referring to the upper level user facing API for loading data into a users deployed environment (be it, HPC, Cloud or PC). As I understand it that API is the datacube.load() call and load_data as @Kirill888 points out is the lower level one for the single node or dask as currently implemented.

It seems the alternate implementations for load_data work along the lines I was suggesting for the additional error handling - allowing alternate implementation below the level of datacube.load() whilst presenting the same API and behaviour to the application code. That way application code is portable between deployment environments from small to large scale. Would end up being something like:

datacube.load()
  preallocateStorage()
    call function to preallocate according the deployed environment choices
  if no error
     call load_data according to the deployment environment choices

It could be done at the Execution Engine level, but I can't see the need - EE.datacube.load() would be confusing.
