### ISSUE TITLE
Ingest should report product changes differences when detected

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#424]
When running `datacube ingest` on a product that already exists, code verifies that the destination product matches the definition supplied in the ingestor config. If the two are not exactly the same `datacube ingest` gives up with an error

```
Ingest config differs from the existing output product, 
but allow_product_changes=False 
```

and gives no indication to the user as to what changes were detected. Actual changes are actually available to ingestor code already:

https://github.com/opendatacube/datacube-core/blob/b987f362ed693408fd746fe8dcf5b0995a44c8fc/datacube/scripts/ingest.py#L140-L146

Changes are returned and are classified into `safe` and `unsafe` categories, displaying those to the user would be super useful.

**Comment by omad** [comment]
I've implemented a fix to this, logging the `safe_changes` and `unsafe_changes` variables before raising an error. However, this was already happening if run as `datacube -v ingest`.

I'd prefer not to merge in this change, since it makes the code even more complicated, and I think we should aim for something even better.

At the moment we have a combination of `print()`, `click.echo()`, `LOG.info/debug()` dying with Stack Traces for sending messages to log files and to the user. We should detect when run in an interactive environment (`isatty()`), and return usefully detailed error messages instead of stack traces and log messages.
