### ISSUE TITLE
Enable per pixel metadata/provenance tracking

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#43]
to enable provenance tracking on a per pixel level - investigate methods which may enable tracing of pixel provenance where the contents of a storage unit may have mixed provenance i.e. Landsat scene overlap

**Comment by omad** [comment]
How often will knowledge of pixel level provenance be required? From my understanding, it must be available, but wouldn't be needed to be saved in high resolution on disk.

At the moment the database records indicate which datasets are used to produce a storage units, from which it's possible to compute per-pixel provenance.

The extra (probably crazy) step, would be storing this provenance information in the storage units as a variable, but I don't see any benefit for doing this, since it won't be necessary for general usage. And it increases both storage overhead and code complexity.

**Comment by petescarth** [comment]
Suspect it would start to get very busy quickly. As an example, the seasonal ground cover composites use pretty much every landsat pixel (will all the masking and shadow and water...) to make a prediction for every date so the metadata soon blows out. We (JRSRP) currently have an issue raised looking and compression and truncation methods for these higher level products so the provenance can be recreated easily, just not necessarily stored within every file.
