### ISSUE TITLE
Use of unescaped strings for generating DB queries

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#464]
User management functions in `/drivers/postgres/_api.py` use `String.format` instead of relying on safer query building formatting provided by `connection.execute`

https://github.com/opendatacube/datacube-core/blob/5f7211d2eb26ac10d6dfb754418d4bd3079cdf7a/datacube/drivers/postgres/_api.py#L878-L881

**Comment by dlubawy-ama** [comment]
I can take this one for the Bug Squash.

**Comment by dlubawy-ama** [comment]
Seems you can't use SQLAlchemy to escape usernames or roles because it wraps them in single quotes which make the PostgreSQL command fail. It works for passwords and description though so I've made that change, but due to the mentioned single quote problem I've kept String.format for the username and roles.
