### ISSUE TITLE
Is it possible to share the datacube i have prepared with others?

### ISSUE THREAD

**Issue by Sumana18** [opendatacube/datacube-core#492]
### Actual behaviour

... eg. Incorrect result, python stacktrace, etc. ...

### Steps to reproduce the behaviour

... Include code, command line parameters as appropriate ...

### Environment information

* Which ``datacube --version`` are you using?
* What datacube deployment/enviornment are you running against?

**Comment by GypsyBojangles** [comment]
Hi @sumana18, apologies for the late response - depending on what you mean by "share" ODC does not have it's own means of exporting index/database state - although PGDump works, assuming all your paths on disk to your data remain consistant. Generally we recommend exporting your product config and dataset YAMLs and re-adding them to ensure your paths are correct.

 Just an FYI, a better medium for questions like this rather than issues with the code would be our Slack channel: http://slack.opendatacube.org/, feel free to join us there :).
