### ISSUE TITLE
Joining Slack group

### ISSUE THREAD

**Issue by davecollett** [opendatacube/datacube-core#650]
Hi,
Is it possible to join the slack channel without the @csiro.au, @ga.gov.au, @nci.org.au, @nasa.gov, @ama-inc.com, @usgs.gov, @anu.edu.au, @bu.edu, @cnes.fr, @esa.int, @inpe.br, @ext.jrc.ec.europa.eu, @dpi.nsw.gov.au, @mdba.gov.au, @data61.csiro.au, @ideam.gov.c, @ideam.gov.co, or @sa.catapult.org.uk email addresses?

**Comment by omad** [comment]
Hi Dave,

Yes absolutely, if you follow the link from the front of the repository (http://slack.opendatacube.org) you can use any email address to join. 

Sorry about the extra step of requesting an invite. It's necessary due to the intended audience of Slack.

We are talking about moving away from Slack to another platform, due to this and other problems with it, but it's not happening yet.

Cheers

**Comment by davecollett** [comment]
Brilliant, thanks very much. Sorry, it looks like it was a network error at my end- the slack.opendatacube.org link was timing out on my laptop. But I could see https://opendatacube.slack.com/signup
I'm in now.
