### ISSUE TITLE
storage unit file name conventions

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#67]
Storage units are currently named with the start time for the earliest timeslice with no end time. 
We have not settled on a timespan for storage units and this should be configurable - i.e. in the storage mapping? Initial thinking was that the timespan for storage units could be controlled through operations but this is not ideal. Spatial index uses the bottom right corner so possibly a similar convention for time could exist i.e. indexed by start time - span is yearly, monthly, daily etc. as defined in storage mapping.

**Comment by mpaget** [comment]
I would suspect/hope that file names shouldn’t materially matter, i.e files are indexed and that’s it.

That said, I appreciate consistency is very useful – including for thredds access and other file system tasks. The start time is as a good a convention as any.

**Comment by woodcockr** [comment]
Whilst the AGDC is filename agnostic, we do need to take a little care with how DOI's are handled in the NERDIP case where the filename appears in THREDDS. If a DOI is issued against a filename the AGDC would effectively become bound by that storage unit time boundary (and any other metadata embedded in the filename). I don't have any real information on NERDIP but it would be worth checking what information becomes fixed in the NERDIP environment which is not AGDC Index store aware.
This is actually one of the reasons I liked the AGDC's Index Store in the first place - it decoupled a physical and performance related storage thing from the metadata and operations seen by the user of the API.

**Comment by v0lat1le** [comment]
Having storage unit filename composed out of its grid index allows access to data without looking up filename anywhere for the case when the region of interest is known. This is used in GDF trial get_data to bypass database access.

**Comment by woodcockr** [comment]
Yes, and I was never really comfortable with that. I can see that being brittle and couldn't quite understand why it was done that way given the get_descriptor can contain all the information necessary for a computational node to not have to hit the database. I didn't sweat it though for the trial which was a time limited prototype of some new ideas.
Note this needs to be robust across collections and I can see the various grids that are likely to result killing any effective away of dealing with metadata in file names.

**Comment by simonaoliver** [comment]
If we go with the concept of temporal stacks being: yearly, daily, monthly, then the we could do something like below:

From the storage unit configuration -
file_path_template: '{platform[code]}_{instrument[name]}_{product_code}_{EPSG:code}_{res_x}_{tile_index[0]}_{tile_index[1]}_{temporal_stack_period_beginning_of}_{collection_id}.nc'

eg. 
SENTINEL_2A_MSI_L1C_3577_25_200000_-300000_2015_1.0.0.nc
SENTINEL_2A_MSI_L1C_4326_0.00025_132_-26_2015_1.0.0.nc

saving characters:
S2AMSI1C_3577_25_200000_-300000_2015_1.0.0.nc
S2AMSI1C_4326_0.00025_132_-26_2015_1.0.0.nc

**Comment by woodcockr** [comment]
I am not sure where this design discussion on the filename convention has got to but I am concerned about the use of the filename structure in code as logic:

```
nbars = [make_storage_unit(su) for su in sus if 'PQ' not in su.path]
pqs = [make_storage_unit(su) for su in sus if 'PQ' in su.path]
```

lines 152 and 153 from agdc-v2/examples/band_stats.py

This type of code would mean the the filenames now create coding dependencies.
Would this not be better served, and more robust, if the storage unit descriptor metadata was used for this logic?
What happens when multiple Collection types are used?

I'm not suggesting for a moment the filename convention shouldn't contain useful information, particularly given they are used in the THREDDS delivery system and its helps troubleshooting. I am concerned that AGDC code based shouldn't be reliant on these for logic, and should use the metadata that can be obtained from the index store.

**Comment by v0lat1le** [comment]
@woodcockr the script is out of date and has become more of a playground to test ideas rather then an example of usage. An issue (#82) has been created to update the example

**Comment by v0lat1le** [comment]
Currently the following fields are supported:
- type_id - storage type id
- type_name - storage type name
- random - 16 random bytes represented as a hex string (32 characters)
- tile_index - 2-value array corresponding to the tile location in the grid
- start_time - string corresponding to the start time of the aggregation period
- end_time - string corresponding to the end time of the aggregation period
- anything from storage type match metadata. Basically those:
  - product_type
  - platform[code]
  - instrument[name]

**Comment by v0lat1le** [comment]
Things that are defined in the storage_type don't even need to be fields - they are the same for each storage unit and can be just 'hardcoded' in the filename pattern.

So type_id, type_name, product, platform, instrument, EPSG code, resolution can all go. Only things that vary cross storage units are the coordinates.
