### ISSUE TITLE
Error when initialize the database

### ISSUE THREAD

**Issue by laminekebe** [opendatacube/datacube-core#675]
When i put this command : datacube -v system init , the output are there :

Initialising database...
2019-03-03 01:33:35,308 459 datacube.drivers.postgres._core INFO Ensuring user roles.
2019-03-03 01:33:35,353 459 datacube.drivers.postgres._core INFO Adding role grants.
Updated.
Checking indexes/views.
2019-03-03 01:33:35,368 459 datacube.drivers.postgres._api INFO Checking dynamic views/indexes. (rebuild views=True, indexes=False)
Done.

And when i show the tables of database , is empty. All of query in jupyter notebook , for example :
products_info = dc.list_products()
the output is empty too. I think that in it has a problem in the database .
PLease solutions?

REgards

**Comment by alexgleith** [comment]
Hey @laminekebe, we're hoping that people ask these kinds of questions on https://gis.stackexchange.com/, just for future reference!

Regarding your issue here, could you please let me know what version of the ODC you're using. Also, are you sure that you're using the same configuration file on init and on querying for products?

Finally, note that the ODC creates a database and schema, so `opendatacube` is the DB and `agdc` is the database, by default.

![image](https://user-images.githubusercontent.com/3445853/53707022-2725c200-3e81-11e9-8f70-eda0a9196391.png)

**Comment by Kirill888** [comment]
@laminekebe `datacube system init` does not populate database with sample products or data, so you do expect empty product list. @alexgleith what's our current best doco for getting started from scratch as far as populating ODC with some data?

**Comment by alexgleith** [comment]
There's a couple of approaches to getting started.

One is the practical approach, so have a look at what we do with the [Cube in a Box](https://github.com/opendatacube/cube-in-a-box).

The second approach is to [read the ODC indexing documentation](https://datacube-core.readthedocs.io/en/latest/ops/indexing.html).

There are [example product definitions here](https://github.com/opendatacube/datacube-dataset-config/tree/master/products).

**Comment by Kirill888** [comment]
looks like "documentation not setting correct expectations" issue, so closing this
