### ISSUE TITLE
numpy version required => 1.9

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#68]
Update setup.py requires to include numpy >1.9 for numpy.linspace dtype support
Other option is to remove dtype flag from pynb examples (dtype of coordinate bands) - fix so we don't have this dependency?

**Comment by mpaget** [comment]
Not sure if this requires a comment but nevertheless..

Agreed. Numpy.linspace is handy and dtype support where necessary/appropriate should be supported. The alternative of creating hacks in the code to enable new features based on old library versions is not within scope I believe. Conversely, enforcing a minimum version level for base libraries is appropriate for development. There may come a time where operational data cube systems are running that we need to consider base library version upgrades more carefully (just flagging this potential future scenario, although I still prefer that we use recent libraries rather than add specific work-arounds to our code).

On a practical level, presumably the NCI has numpy >= 1.9 otherwise a request will need to made.
