### ISSUE TITLE
index.datasets.search_returning cannot be used as a performant function relative to index.datasets.search

### ISSUE THREAD

**Issue by ashoka1234** [opendatacube/datacube-core#715]
### Performant per `dataset` processing
We cannot reliably use `index.datasets.search_returning` for performant per dataset processing since it returns results from table joins across `DATASET_SOURCE, DATASET_LOCATION, DATASET, DATASET_TYPE`,  and `METADATA_TYPE`, if selected fields are to be extracted from any of those tables. It seems we can use `index.datasets.search` for per dataset processing but lacks memory (perhaps speed as well) efficiency of `index.datasets.search_returning`. Both these functions share 
`drivers.postgres.search_datasets` which in turn rely on `drivers.postgres.search_datasets_query`. the issue is that `index.datasets.search_returning` derives its possible multiple results per dataset behaviour from `drivers.postgres.search_datasets_query`. The `drivers.postgres.search_datasets_query` function treats `select_columns` differently depending on how `select_columns` are specified. Specifically `DATASET <-> DATASET_LOCATION` relationship is treated differently when you are on the `index.datasets.search` pathway and  `index.datasets.search_returning` pathway.

The behaviour of `index.datasets.search_returning` seems intentional as per its doc-string  `... It also allows for returning rows other than datasets, such as a row per uri when requesting field 'uri' ...` but it is risky to use it as an alternative performant search function relative to  `index.datasets.search`. To design a performant search function that returns only selected fields but that can be used for per dataset processing we need changes to database layer, specifically, either we have to change `drivers.postgres.search_datasets_query` bahaviour or write a new one.

**Comment by jeremyh** [comment]
If I understand correctly, the underlying issue is that `search()` returns dataset objects which each have a `.uris` list of uris. But there is no equivalent `uris` field to ask for from `search_returning()`.  

The only field we have is a confusing `uri` field (note the singular) which returns search results as one-per-uri instead of one-per-dataset. But this change in row-selection is problematic for many usecases (no results if no uris!), and the different semantics make it hard to replace existing `search()` usage with `search_returning()` without a lot of duplication.

Perhaps we could add a field that matches Dataset's `.uris` property exactly: call it "uris" and have it return an array. Therefore it wouldn't affect the per-dataset row selection, and `searching_returning()` could be used as a drop-in replacement for `search()` in all cases. Would that suit your use-case?

**Comment by ashoka1234** [comment]
Yeah! that sounds like a good idea for few use cases. Another hard but related issue is that I would like some sort of extraction of `DATASET_LOCATION.id` per dataset (More ideal solution for me for this, though, have a new auto-incremented key field in DATASET table!) for `paging` queries.

**Comment by jeremyh** [comment]
We enforce the location to be unique per dataset, so most of the older api methods use the tuple `dataset_id, uri` as a unique id. The integer primary key (along with product's) was originally intended as a driver implementation detail and not part of the api. I don't know whether it's worth changing: depends on the use case you have in mind.

For unique paging of datasets within Explorer I'm currently using a `time, dataset_id` tuple -- I think time is more natural than dataset insertion/index order (ie. incrementing primary key) for most of our existing datacubes.

**Comment by ashoka1234** [comment]
OK I thought about `dataset_id` alone as well as using `time`. Only thing that troubled me was that new `dataset` inserts would get inserted all over within the `dataset_id` order. Since `dataset_id` is secondary in the `time, dataset_id`  index order this may not be that much of an issue. Though dataset deletions can change page workflow I was more attracted to static nature that auto-incremented id gives. But if you have good experience with `time, dataset_id` tuple then that would be a good candidate to lean on for paging.
