### ISSUE TITLE
Support GDAL "/vsi*" paths directly

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#824]
Normally we rely on URL syntax for defining paths to assets of a dataset. `rasterio` library converts those to GDAL's VSI syntax for us. For example `https://host.tld/file.tif` will become `/vsicurl/https://host.tld/file.tif`. Nesting is also supported via `+`, for example `http+zip://`.

Sometimes however one needs to fallback to raw GDAL syntax. It should be possible to define dataset location as GDAL vsi path.

**Comment by Kirill888** [comment]
Looks like netcdf over http case requires `vsicurl/` paths right now as it's not clear how to specify band names in the url syntax and `vsi` fallback can be used in the interim.

**Comment by alfredoahds** [comment]
This used to be something we could simply handle on the driver level by having our compatibility layer return `Dataset` objects with a custom `uri_scheme` defined that would route the rasters through our driver, but v1.7 started parsing the uri_scheme from the uri rather than pulling it from the `Dataset` objects. I've been tinkering with restoring that sort of scheme on our end but it'll involve some gross stuff like prepending `vsicurl://` then making required modifications to the uri elsewhere.  

Re: netCDF vsicurl usage, we're formatting 'uri's that look like: `netCDF:/vsicurl/"https://{url}":{band_name}"'` and it works fine. Unfortunately GDAL/rasterio doesn't recognize netCDF files properly without the vsicurl designation.

**Comment by Kirill888** [comment]
Thanks @alfredoahds so we need to detect all "HDF:" prefixes as well as `/vsi.*` for "raw gdal syntax" paths.

**Comment by Kirill888** [comment]
I guess alternative is to still "wrap" path in `NETCDF:"{file|vsi path}":band`, and just detect `vsi_path` strings.

**Comment by snowman2** [comment]
I think the simplest solution would be to add support in rasterio directly. In this scenario, no `vsicurl` support needed in datacube. Issue about it here: https://github.com/mapbox/rasterio/issues/1838.

**Comment by Kirill888** [comment]
@snowman2 agree, but having fallback to gdal vsi paths be available is still useful.

**Comment by snowman2** [comment]
> having fallback to gdal vsi paths be available is still useful.

Agreed 👍
