### ISSUE TITLE
Can not configure resampling/fuser using measurement alias, but probably want to

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#887]
Per band resampling was added (9dd4131b2ebcc74eb0bd622aac9634335fc134e8) soon after alias support was introduced (901c472ba80a049392294e84160d5080da64072d), but it looks like code always assumed that `resampling` dictionary contains "canonical" band names and not "aliases".

This is an error. If requesting `fmask` band to be read with `nearest` resampling one should not need to know canonical name of the band in order to configure that.

**Comment by robbibt** [comment]
This issue affects functions like `load_ard` from DEA notebooks, which loads `fmask` differently depending on whether the band is requested manually using `measurements` or automatically when no measurements is provided (see discussion in https://github.com/GeoscienceAustralia/dea-notebooks/pull/527). Because `fmask`'s aliases also differ on Landsat vs. Sentinel 2, the user may not be aware of what alias is actually being used to load `fmask` behind the scenes.

Currently, the only work-around to ensure that `fmask` is re-sampled correctly is to pass in a dict containing both band name/alias options (e.g. both `fmask` and `oa_fmask`):

`resampling={'*': 'cubic', 'fmask': 'nearest', 'oa_fmask': 'nearest'}`

**Comment by Kirill888** [comment]
@uchchwhash I think confusion stems from this function:

https://github.com/opendatacube/datacube-core/blob/c5a7192b5a5d82dd8d1ee3cfc67732c86f6bc680/datacube/model/__init__.py#L478-L488

This takes on input `name|alias`, but produces on output `name->Measurement`, I think it is confusing. I think same keys that were used to request measurement should also appear in the output. Furthermore returned `Measurement` class should be modified on the fly to contain requested alias as an actual name.

`Measurement` objects are already constructed on the fly anyway (not cached), so pretending that it was named `fmask` and not `oa_fmask` in a first place is reasonable. This will then fix problems with resampling/fusing name confusion and eliminate the need to run `apply_aliases` as all variables will be named appropriately from the start.

**Comment by uchchwhash** [comment]
Will `load_data` understand it then?

**Comment by Kirill888** [comment]
yes it just uses `.name` on the measurement object, it doesn't touch product spec/definition

**Comment by Kirill888** [comment]
This would also fix dask task names being weird (currently uses canonical names instead of what user requested)
