### ISSUE TITLE
Sinusoidal projection support in CF

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#92]
DRAFT Storage configurations have been included https://github.com/data-cube/agdc-v2/tree/develop/docs/config_samples/modis to enable write of MODIS USGS data to sinusoidal projection storage units. This projection does not look to be currently supported in CF. THREDDS issues?

**Comment by mpaget** [comment]
No issues. I'll follow up with the detail of ingesting MCD43A1-4 c5 and c6 in the coming days - to have it working by wgiss/hackfest time.

Just because CF does not support a projection does not preclude that projection from being supported by the data cube. If a projection is not supported by CF then that only raises questions for the netcdf-cf storage units particularly in the NCI context, which can be managed by other processes (i.e, a recognition in the NCI and custodian metadata systems that the storage units are not 100% CF compliant for known reasons).

And thank you for adding sinusoidal support to the ingest framework!

**Comment by omad** [comment]
There's an open proposal for adding Sinusoidal Projection support to the CF Conventions http://cf-trac.llnl.gov/trac/ticket/77 . The proposal was accepted in 2012 for inclusion in the next version of the Conventions, but hasn't happened yet.

**Comment by mpaget** [comment]
Great, thank you.
As its an approved proposal its worth prodding the CF folks for the "next version".
I think I recall that a csiro person had been invited to a mini workshop on cf and/or thredds development. I'll follow this up and see if there's an opportunity to engage.

**Comment by v0lat1le** [comment]
That CF ticket (http://cf-trac.llnl.gov/trac/ticket/77) confuses me...
They propose to use **longitude_of_projection_origin** for the longitude of central meridian, while the sample data uses **longitude_of_central_meridian** and **longitude_of_prime_meridian**.

Currently we put in **longitude_of_central_meridian**. I guess we could put in all three?
