### ISSUE TITLE
Unique constraint failure "pg_class_relname_nsp_index" on rerunning `system init`

### ISSUE THREAD

**Issue by whatnick** [opendatacube/datacube-core#962]
### Expected behaviour
Datacube system init cannot be interrupted.

### Actual behaviour

Datacube system init if interrupted during dynamic index creation breaks on re-runs.

### Steps to reproduce the behaviour

```
'2020-06-18 03:27:19,676 1 datacube.drivers.postgres._dynamic INFO Creating index: dix_ls8_pq_oli_scene_sat_path_sat_row_time\n'
'Traceback (most recent call last):\n'
'  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context\n'
'    cursor, statement, parameters, context\n'
'  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute\n'
'    cursor.execute(statement, parameters)\n'
'psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_class_relname_nsp_index"\n'
'DETAIL:  Key (relname, relnamespace)=(dix_ls8_pq_oli_scene_sat_path_sat_row_time, 157114366) already exists.\n'
'\n'
'\n'
'The above exception was the direct cause of the following exception:\n'
'\n'
'Traceback (most recent call last):\n'
'  File "/env/bin/datacube", line 8, in <module>\n'
'    sys.exit(cli())\n'
'  File "/env/lib/python3.6/site-packages/click/core.py", line 829, in __call__\n'
'    return self.main(*args, **kwargs)\n'
'  File "/env/lib/python3.6/site-packages/click/core.py", line 782, in main\n'
'    rv = self.invoke(ctx)\n'
'  File "/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke\n'
'    return _process_result(sub_ctx.command.invoke(sub_ctx))\n'
'  File "/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke\n'
'    return _process_result(sub_ctx.command.invoke(sub_ctx))\n'
'  File "/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke\n'
'    return ctx.invoke(self.callback, **ctx.params)\n'
'  File "/env/lib/python3.6/site-packages/click/core.py", line 610, in invoke\n'
'    return callback(*args, **kwargs)\n'
'  File "/env/lib/python3.6/site-packages/datacube/ui/click.py", line 197, in new_func\n'
'    return f(parsed_config, *args, **kwargs)\n'
'  File "/env/lib/python3.6/site-packages/datacube/ui/click.py", line 229, in with_index\n'
'    return f(index, *args, **kwargs)\n'
'  File "/env/lib/python3.6/site-packages/datacube/scripts/system.py", line 59, in database_init\n'
'    rebuild_views=recreate_views or rebuild,\n'
'  File "/env/lib/python3.6/site-packages/datacube/index/_metadata_types.py", line 226, in check_field_indexes\n'
'    rebuild_views=rebuild_views,\n'
'  File "/env/lib/python3.6/site-packages/datacube/drivers/postgres/_api.py", line 855, in check_dynamic_fields\n'
'    concurrently=concurrently,\n'
'  File "/env/lib/python3.6/site-packages/datacube/drivers/postgres/_api.py", line 877, in _setup_metadata_type_fields\n'
'    concurrently=concurrently\n'
'  File "/env/lib/python3.6/site-packages/datacube/drivers/postgres/_api.py", line 887, in _setup_product_fields\n'
'    rebuild_indexes=rebuild_indexes, rebuild_view=rebuild_view)\n'
'  File "/env/lib/python3.6/site-packages/datacube/drivers/postgres/_dynamic.py", line 94, in check_dynamic_fields\n'
"    index_type='gist'\n"
'  File "/env/lib/python3.6/site-packages/datacube/drivers/postgres/_dynamic.py", line 161, in _check_field_index\n'
'    index.create(conn)\n'
'  File "/env/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 3831, in create\n'
'    bind._run_visitor(ddl.SchemaGenerator, self)\n'
'  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1663, in _run_visitor\n'
'    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)\n'
'  File "/env/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 144, in traverse_single\n'
'    return meth(obj, **kw)\n'
'  File "/env/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 868, in visit_index\n'
'    self.connection.execute(CreateIndex(index))\n'
'  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1020, in execute\n'
'    return meth(self, multiparams, params)\n'
'  File "/env/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection\n'
'    return connection._execute_ddl(self, multiparams, params)\n'
'  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1082, in _execute_ddl\n'
'    compiled,\n'
'  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1324, in _execute_context\n'
'    e, statement, parameters, cursor, context\n'
'  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception\n'
'    sqlalchemy_exception, with_traceback=exc_info[2], from_=e\n'
'  File "/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_\n'
'    raise exception\n'
'  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context\n'
'    cursor, statement, parameters, context\n'
'  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute\n'
'    cursor.execute(statement, parameters)\n'
'sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pg_class_relname_nsp_index"\n'
'DETAIL:  Key (relname, relnamespace)=(dix_ls8_pq_oli_scene_sat_path_sat_row_time, 157114366) already exists.\n'
'\n'
"[SQL: CREATE INDEX dix_ls8_pq_oli_scene_sat_path_sat_row_time ON agdc.dataset USING gist (numrange(CAST(metadata #>> '{image, satellite_ref_point_start, x}' AS NUMERIC), greatest(CAST(metadata #>> '{image, satellite_ref_point_end, x}' AS NUMERIC), CAST(metadata #>> '{image, satellite_ref_point_start, x}' AS NUMERIC)), '[]'), numrange(CAST(metadata #>> '{image, satellite_ref_point_start, y}' AS NUMERIC), greatest(CAST(metadata #>> '{image, satellite_ref_point_end, y}' AS NUMERIC), CAST(metadata #>> '{image, satellite_ref_point_start, y}' AS NUMERIC)), '[]'), tstzrange(least(agdc.common_timestamp(metadata #>> '{extent, from_dt}'), agdc.common_timestamp(metadata #>> '{extent, center_dt}')), greatest(agdc.common_timestamp(metadata #>> '{extent, to_dt}'), agdc.common_timestamp(metadata #>> '{extent, center_dt}')), '[]')) WHERE archived IS NULL AND dataset_type_ref = 59]\n"
'(Background on this error at: http://sqlalche.me/e/gkpj)\n'
```

### Environment information

* Which ``datacube --version`` are you using? 1.8.0
* What datacube deployment/enviornment are you running against? NCI DB

**Comment by jeremyh** [comment]
Interesting. That unique constraint is on a system table, not one of ours. But normally when hitting that type of duplicate there's a friendlier message from postgres ("relation "dix_ls8..." already exists").

Could two instances have been running at the same time?

Or from your description: maybe the first connection to NCI was interrupted but the query kept running in the background, and so when it reconnected and retried it now had two "create indexes" going at the same time in separate transactions.

**Comment by jeremyh** [comment]
Does it work if you rerun it now? That would suggest it may have been two concurrently-running inits.

If it's consistently failing now, then it may be something else, like a corrupt index.

**Comment by jeremyh** [comment]
(note that by default our indexes are created using postgres' `concurrently` flag, which can always leave an invalid index behind. Datacube doesn't currently check for invalid indexes, though I haven't seen any in practice so far. Invalid ones will show up as such in psql `\d <table>`)

**Comment by Kirill888** [comment]
@jeremyh should `system init` NOT use `concurrently` flag?

**Comment by Kirill888** [comment]
Are we sure this is due to `system init` being interrupted and not due to `product add` being interrupted, there seem to be already some products in that log.

**Comment by jeremyh** [comment]
In theory `system init` is supposed to handle interrupted products-adds, as it checks and creates any missing indexes. So I'd still consider it a `system init` bug if that's happening.

But I do suspect this was from parallel-running-`init`s  — we don't have any protections against it at the moment, and it would likely raise an error like this. The first, interrupted `create-index` finishes in the background, while the immediately-rerun `create-index` finishes second in a separate transaction and finds the index already exists on commit. 

It doesn't actually leave the datacube in a bad state, but does give you an unpleasant error.

> @jeremyh should `system init` NOT use `concurrently` flag?

It uses `concurrently` by default to avoid taking a lock on the table, since there are other users and jobs running in our environments that we'd rather not block (...and potentially cause timeout failures) for the many-minutes it can take to run.

You can allow a table-lock by passing `--lock-table` to `system init`, in which case it doesn't use `concurrently`. 

Maybe avoiding the locks by default is being too conservative, but the speed increase from allowing table lock was pretty modest last I tried it. 

With locks we could create products in a single transaction, though, which the current `--allow-exclusive-lock` on `product add` doesn't seem to take advantage of. That would make it "harder" to add products (they do seem to get interrupted very often), but would avoid people needing to rerun `system init` sometimes, or else having a quietly slow datacube. The critical steps do happen in a transaction, just not the dynamic indexes.

--- 

I do think we could, at least, make `init` query for invalid indexes, as it could easily fix them, and we don't currently make it obvious to users that they can happen.  But as I said: we haven't seen any in the wild yet, and I doubt it's causing the issue here.

**Comment by Kirill888** [comment]
Thanks Jeremy, I didn't realise that there is a use case for running `system init` on an already initialised and used by readers database.

We have certainly encountered "broken indexes" due to interrupted product add. By "broken indexes" I mean "queries are slow, maybe because index is missing", not "corrupt on disk" indexes.

@whatnick maybe some of bootstrapping scripts should use those "slower but safer" command line options that are available?

**Comment by whatnick** [comment]
After discussions with @omad it seems 2 concurrent runs are to blame. Client lost connection to the DB and has a retry interval of 5 minutes , so when it retried another instance of dynamic index creation was already running and I got this error. In the future I will increase retry interval to a large number like 15-20 minutes to prevent piling up.
